### ISSUE TITLE
Character limit for service URL is set to 200 for saved map session in GeoNode

### ISSUE THREAD

**Issue by darinacosta** [boundlessgeo/exchange#10]
Maybe this should change, maybe not, but might be worth considering?: https://github.com/GeoNode/geonode/blob/master/geonode/maps/models.py#L426

This presented a problem when an Exchange user attempted to save a map after adding this service url:
https://firms.modaps.eosdis.nasa.gov/wms-t/viirs/?TIME=-24hours&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities&LAYERS=VIIRS_Hotspots&width=512&height=512&BBOX=-20037508.3427892480,-20037508.3427892480,20037508.3427892480,20037508.3427892480&SRS=EPSG:3857

From the Django docs:
```
Like all CharField subclasses, URLField takes the optional max_length argument. If you don't specify max_length, a default of 200 is used.
```

**Comment by darinacosta** [comment]
If we do decide to change the character limit, existing GeoNode instances will have to run migrations in order to update their databases. After updating, run this from the directory containing manage.py:

```
1. python manage.py makemigrations
2. python manage.py migrate
```

Complete migration docs are [here](https://docs.djangoproject.com/en/1.9/topics/migrations/).

**Comment by BerryDaniel** [comment]
With registry being used rather than remote services this can now be closed.
