### ISSUE TITLE
Conflict between GeoNode & Exchange INSTALLED_APPS: corsheaders

### ISSUE THREAD

**Issue by sarasafavi** [boundlessgeo/exchange#113]
_initially reported at https://github.com/boundlessgeo/exchange/issues/109_

_Known issue:_ on Nov 11 the app `corsheaders` was added to GeoNode master (see: https://github.com/GeoNode/geonode/commit/36d4ff285567c9bb5cf92900c8440631c307817e). Since this app is also in Exchange's settings, this causes a Django error due to multiple INSTALLED_APPS with the same name.

This should only affect development (using GeoNode master). As a workaround, comment out Exchange's `corsheaders` line in https://github.com/boundlessgeo/exchange/blob/master/exchange/settings/default.py#L129.

TODO: once we bump the pinned GeoNode version in Exchange, this line should be removed from default settings.

**Comment by BerryDaniel** [comment]
https://github.com/GeoNode/geonode/commit/1898779e8cdf104ac454bc497c6243d19f7caf90

fixed upstream
