### ISSUE TITLE
Missing CSS Folder on pip install

### ISSUE THREAD

**Issue by benhosmer** [boundlessgeo/exchange#127]
The commit that exchange is using from [osgeo_importer](https://github.com/GeoNode/django-osgeo-importer) doesn't seem to have a `/css` folder:

```
copying osgeo_importer/static/osgeo_importer/Makefile -> build/lib/osgeo_importer/static/osgeo_importer
    error: can't copy 'osgeo_importer/static/osgeo_importer/css': doesn't exist or not a regular file
```

If I change this line in the `requirements.txt`:

```
24 git+git://github.com/boundlessgeo/django-osgeo-importer@b77ea961ea458b9c2ed8388ce7011a43e29f6fe9#egg=    django-osgeo-importer
```

To point to latest, `pip install -r requirements.txt` completes without any errors.

**Comment by BerryDaniel** [comment]
osgeo_importer is still in development and as of now is not included in any production version of exchange. We are currently working on cleaning up the requirements files to allow for a dev (osgeo_importer included) and prod. https://github.com/boundlessgeo/exchange/pull/123

**Comment by benhosmer** [comment]
@BerryDaniel I just fetched from HEAD and this issue no longer exists. Unless you think it should remain open, I'll close it.
