### ISSUE TITLE
Is it possible to use Redis instead of RabbitMQ for Celery queue

### ISSUE THREAD

**Issue by JJediny** [boundlessgeo/exchange#144]
Trying to test out of deployment onto cloud.gov but there is no support for rabbitmq as a cf service. @BerryDaniel

**Comment by BerryDaniel** [comment]
@JJediny can you test it out in your env? 

configuration can be found here http://docs.celeryproject.org/en/3.1/configuration.html#redis-backend-settings

**Comment by BerryDaniel** [comment]
Packages are in place to support redis
