### ISSUE TITLE
Error when running docker-compose 

### ISSUE THREAD

**Issue by firmanhadi** [boundlessgeo/exchange#188]
Hi all,

I have successfully installed Exchange on Centos 7 in VM using Docker but failed on Centos 7 in dedicated machine.

Here is the error code:

Step 9/11 : RUN rm -rf /env/lib/python2.7/site-packages/maploom/static/maploom &&     ln -s /mnt/maploom/build /env/lib/python2.7/site-packages/maploom/static/maploom &&     rm /env/lib/python2.7/site-packages/maploom/templates/maps/maploom.html &&     ln -s /mnt/maploom/build/maploom.html /env/lib/python2.7/site-packages/maploom/templates/maps/maploom.html
 ---> Running in ead159664144
rm: cannot remove `/env/lib/python2.7/site-packages/maploom/static/maploom/assets': Directory not empty
rm: cannot remove `/env/lib/python2.7/site-packages/maploom/static/maploom/fonts': Directory not empty
ERROR: Service 'exchange' failed to build: The command '/bin/sh -c rm -rf /env/lib/python2.7/site-packages/maploom/static/maploom &&     ln -s /mnt/maploom/build /env/lib/python2.7/site-packages/maploom/static/maploom &&     rm /env/lib/python2.7/site-packages/maploom/templates/maps/maploom.html &&     ln -s /mnt/maploom/build/maploom.html /env/lib/python2.7/site-packages/maploom/templates/maps/maploom.html' returned a non-zero code: 1

**Comment by walker** [comment]
@firmanhadi We've made some changes to the docker-compose files that hopefully fix these issues.

Also, please ensure you check the readme in the docker folder for instructions.
