### ISSUE TITLE
layers attribute value with arabic characters not displaying

### ISSUE THREAD

**Issue by hishamkaram** [boundlessgeo/exchange#264]
layers attribute value with arabic characters not displaying with exchange however arabic characters working fine in geonode
Note: I am using docker
![screenshot_2017-04-20_11-43-48](https://cloud.githubusercontent.com/assets/24391550/25224514/e2accf88-25be-11e7-8d8f-760202538dc7.png)

**Comment by walker** [comment]
I don't think that version of our Boundless SDK (javascript mapping SDK supports Arabic), we'll be updating the map viewers coming up.
