### ISSUE TITLE
Missing PostGIS when standing up with Vagrant 

### ISSUE THREAD

**Issue by richard3d** [boundlessgeo/exchange#350]
I am trying to stand up a dev environment with Exchange and everything seems mostly functional however I noticed layers were not being published to GeoServer. Upon further investigation I could not create a PostGIS back end in GeoServer myself. When I started from scratch with ```vagrant up``` I noticed this error ```==> default: ERROR:  could not load library "/usr/pgsql-9.6/lib/postgis-2.3.so": libproj.so.0: cannot open shared object file: No such file or directory
==> default: ERROR:  relation "geometry_columns" does not exist
==> default: ERROR:  relation "spatial_ref_sys" does not exist```

**Comment by bitner** [comment]
I do not believe the vagrant environment for exchange is being maintained at all. The main development environment that is being used is the docker-compose environment.

**Comment by walker** [comment]
Vagrant removed from project & support unless someone wants to take up the cause.
