### ISSUE TITLE
How to access docker exchange from LAN computers?

### ISSUE THREAD

**Issue by lolob** [boundlessgeo/exchange#425]
Hello I need some good tutorial.

I'm running docker-for-linux on machine Ubuntu Server 16.04. Containers that are run on this machine has their own IP. My question is I want to reach the docker-exchange from other machine on the same LAN.

**Comment by walker** [comment]
@lolob very dependent on your network and pretty outside the scope of what we're doing here. You'd be better served by asking this Q on docker-specific sites/resources rather than on this Exchange repo.
