### ISSUE TITLE
Error upload shp

### ISSUE THREAD

**Issue by lolob** [boundlessgeo/exchange#437]
Finally the exchange is up and running. Except import failed when importing shp data. I got this error ``GDAL_ERROR 4: `/scratch/media_root/osgeo_importer_uploads/13/places_Project3857.prj' not recognized as a supported file format.``

**Comment by walker** [comment]
Probably something wrong with the file. Try this one.

[tl_2016_02_bg.zip](https://github.com/boundlessgeo/exchange/files/1482618/tl_2016_02_bg.zip)

**Comment by lolob** [comment]
@walker It doesn't work either
My sample data from here [places.zip] (https://github.com/boundlessgeo/exchange/files/224868/places.zip).

**Comment by lolob** [comment]
@walker Solved. It works, if...
1. Do not set category
2. Do not set time attributes
3. Do not set version control

**Comment by walker** [comment]
Ah...yes, if you're using HEAD, we have an issue in the docker dev environment right now in regards to version control.
