### ISSUE TITLE
Geonode seems not to be installed

### ISSUE THREAD

**Issue by sindile** [boundlessgeo/exchange#93]
I am unable to access exchange and I do not see geonode in my list of containers. Is there a step I am missing? 
I am able to access geoserver, tomcat, nginx and database
I followed the documentation for installing exchange via docker:
1. created a folder - platform
2. cloned into it:
git clone https://github.com/boundlessgeo/exchange.git
git clone -b 2.5.2 https://github.com/geonode/geonode.git
3. changed into directory exchange and modified .env setting to the paths of both exhange and geonode
4. docker-compose up -d
493a9c626969        exchange                   "/root/worker.sh"        About a minute ago   Up About a minute                                                                            worker
d00b3e750a79        nginx                      "nginx -g 'daemon off"   About a minute ago   Up About a minute   80/tcp, 443/tcp                                                          proxy
1815aea5ebdc        exchange                   "/root/exchange.sh"      About a minute ago   Up About a minute   0.0.0.0:32770->80/tcp                                                    exchange
31a0bd5b7527        geoserver                  "catalina.sh run"        About a minute ago   Up About a minute   0.0.0.0:32769->8080/tcp                                                  geoserver
34b47c0450f5        memcached                  "docker-entrypoint.sh"   2 minutes ago        Up About a minute   11211/tcp                                                                cache
5a5dd7279a49        postgres                   "gosu postgres postgr"   2 minutes ago        Up About a minute   5432/tcp                                                                 database
8ea6bd87fd3d        elasticsearch:1.7          "/docker-entrypoint.s"   2 minutes ago        Up About a minute   9200/tcp, 9300/tcp                                                       search
2bf2dfac9e35        rabbitmq:3.6               "docker-entrypoint.sh"   2 minutes ago        Up About a minute   4369/tcp, 5671-5672/tcp, 25672/tcp                                       queue

**Comment by BerryDaniel** [comment]
@sindile the docker setup for exchange is intended for a development environment, it is not intended for production. If you are trying to use the geonode docker setup I would look in the geonode [repo](https://github.com/GeoNode/geonode). If you are wanting a commercially supported version of exchange, please feel free to reach out to our [sales team](http://boundlessgeo.com/request-a-quote/).
